board/urls.py
from django.conf.urls import patterns, include, url
from board.feeds import EventFeed
from board.views import IndexView, ServiceView
from board.api import ServiceResource, CategoryResource, StatusResource, EventsResource
from tastypie.api import Api
from django.contrib import admin

admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(ServiceResource())
v1_api.register(CategoryResource())
v1_api.register(StatusResource())
v1_api.register(EventsResource())

urlpatterns = patterns('',
                       url(r'^$', IndexView.as_view(), name='index'),
                       url(r'^services/(?P<slug>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})$', ServiceView.as_view(), name='service'),
                       url(r'^services/(?P<slug>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})$', ServiceView.as_view(), name='service'),
                       url(r'^services/(?P<slug>[-\w]+)/(?P<year>\d{4})$', ServiceView.as_view(), name='service'),
                       url(r'^services/(?P<slug>[-\w]+)$', ServiceView.as_view(), name='service'),
                       url(r'^feed$', EventFeed(), name='feed'),
                       url(r'^api/', include(v1_api.urls)),
                       url(r'^admin/', include(admin.site.urls)),
                       )

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'login.html'},
        name='mysite_login'),
    url(r'^logout/$', 'logout', {'next_page': '/'}, name='mysite_logout'),
)

board/models.py
from datetime import datetime, date, timedelta
from django.db import models


class Category(models.Model):
    """
    A category grouping services
    """
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'categories'

    def __unicode__(self):
        return self.name


class Service(models.Model):
    """
    A service to track.
    """
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.CharField(max_length=255)
    category = models.ForeignKey(Category, related_name='services', null=True)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return 'service', [self.slug]

    def last_known_event(self, event_date, counter=0):
        temp = Event.objects.filter(service=self,
                                    start__year=event_date.year,
                                    start__month=event_date.month,
                                    start__day=event_date.day)
        if temp:
            temp = temp.order_by('-id')[0]
        else:
            counter += counter + 1
            if counter > 31:
                temp = None
            else:
                temp = self.last_known_event(event_date - timedelta(days=1),
                                             counter)
        return temp

    def last_five_days(self):
        """
        Used on home page.
        """
        lowest = Status.objects.default()
        severity = lowest.severity

        yesterday = date.today() - timedelta(days=1)
        ago = yesterday - timedelta(days=5)

        events = self.events.select_related().filter(start__gt=ago,
                                                     start__lt=date.today())
        stats = {}

        while yesterday > ago:
            temp = self.last_known_event(yesterday)
            if temp:
                image = temp.status.image
            else:
                image = lowest.image
            stats["%s-%s" % (yesterday.month, yesterday.day)] = {
                "image": image,
                "day": yesterday,
            }
            yesterday = yesterday - timedelta(days=1)

        for event in events:
            if event.status.severity > severity:
                issue_date = '%s-%s' % (event.start.month, event.start.day)
                if issue_date in stats.keys():
                    stats[issue_date]["image"] = "information"
                    stats[issue_date]["information"] = True

        results = []

        keys = stats.keys()
        keys.sort()
        keys.reverse()

        for k in keys:
            results.append(stats[k])

        return results

    def current_event(self):
        try:
            t_event = self.events.latest()
            event = {
                'service': t_event.service,
                'status': t_event.status,
                'message': t_event.message,
                'start': t_event.start,
                'informational': t_event.informational,
            }
        except:
            event = None
        return event


class StatusManager(models.Manager):
    def default(self):
        return self.get_query_set().filter(severity=10)[0]


class Status(models.Model):
    """
    A possible system status.
    """
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.CharField(max_length=255)
    SEVERITY_CHOICES = (
        (10, 'NORMAL'),
        (30, 'WARNING'),
        (40, 'ERROR'),
        (50, 'CRITICAL'),
    )
    severity = models.IntegerField(choices=SEVERITY_CHOICES)
    image = models.CharField(max_length=100)

    objects = StatusManager()

    class Meta:
        ordering = ('severity',)
        verbose_name_plural = 'statuses'

    def __unicode__(self):
        return self.name


class Event(models.Model):
    service = models.ForeignKey(Service, related_name='events')
    status = models.ForeignKey(Status, related_name='events')
    message = models.TextField()
    start = models.DateTimeField(default=datetime.now)
    informational = models.BooleanField(default=False)

    class Meta:
        ordering = ('-start',)
        get_latest_by = 'start'

board/views.py
from board.models import Service, Status
import datetime
from django.views.generic import ListView, DetailView
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
import calendar


class BoardMixin(object):
    def get_context_data(self, **kwargs):
        context = super(BoardMixin, self).get_context_data(**kwargs)
        context['statuses'] = Status.objects.all()
        return context


def get_past_days(num):
    date = datetime.date.today()
    dates = []

    for i in range(1, num + 1):
        dates.append(date - datetime.timedelta(days=i))

    return dates


class IndexView(BoardMixin, ListView):
    context_object_name = 'services'
    queryset = Service.objects.all()
    template_name = 'board/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['default'] = Status.objects.default()
        context['past'] = get_past_days(5)
        return context


class ServiceView(BoardMixin, DetailView):
    model = Service
    template_name = 'board/service_detail.html'

    def get(self, request, slug=None, year=None, month=None, day=None):

        data = get_object_or_404(self.model, slug=slug)

        if year:
            year = int(year)
        if month:
            month = int(month)
        if day:
            day = int(day)

        if day:
            start_date = datetime.date(year, month, day)
            end_date = start_date + datetime.timedelta(days=1)
        elif month:
            start_date = datetime.date(year, month, 1)
            days = calendar.monthrange(start_date.year,
                                       start_date.month)[1]
            end_date = start_date + datetime.timedelta(days=days)
        elif year:
            leap = 366 if calendar.isleap(year) else 365
            start_date = datetime.date(year, 1, 1)
            end_date = start_date + datetime.timedelta(days=leap)
        else:
            # get last 30 days
            start_date = datetime.datetime.now() + datetime.timedelta(days=30)
            end_date = datetime.datetime.now()

        events = data.events.filter(start__gte=start_date).filter(start__lt=end_date)

        no_events = None
        if len(events) == 0:
            no_events = 'No events found.'

        return render_to_response(self.template_name, {
            'service': data,
            'events': events,
            'no_events': no_events,
        }, context_instance=RequestContext(request))

templates/base.html
{% load url from future %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{{ current_site.name }}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/lumen/bootstrap.min.css" rel="stylesheet">
{#    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/sandstone/bootstrap.min.css" rel="stylesheet">#}
{#    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/simplex/bootstrap.min.css" rel="stylesheet">#}
{#    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/superhero/bootstrap.min.css" rel="stylesheet">#}
{#    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/united/bootstrap.min.css" rel="stylesheet">#}
{#    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/yeti/bootstrap.min.css" rel="stylesheet">#}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" type="text/css" media="screen">
    <link rel="alternate" type="application/atom+xml" title="Latest status updates." href="{% url 'feed' %}">
</head>
<body>
<div id="wrapper" class="container">
    <div id="header" class="page-header">
        <img id="logo" src="{{ STATIC_URL }}images/logo.png" alt="Logo">

        <h1 id="title"><a href="/">{{ current_site.name }}</a></h1>
        {% block toggle_login %}
            {% include "toggle_login.html" %}
        {% endblock %}
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    <div id="footer">
        <ul class="pull-right">
        </ul>
    </div>
</div>

{% block js %}
{% endblock %}
</body>
</html>

templates/board/_legend.html
<div id="legend">
  <h4>Legend</h4>
  <table class="table table-striped table-hover">
    <tbody>
      {% for status in statuses %}
      <tr>
        <td class="icon">
          <img src="{{ STATIC_URL }}images/status/{{ status.image }}.png" alt="{{ status.name }}" />
        </td>
        <td>{{ status.description }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

templates/board/index.html
{% extends "base.html" %}
{% block content %}
    {% regroup services|dictsort:"category.name" by category as category_list %}
    <div id="webservices" class="frame">
        {% for category in category_list %}
            {% if user.username == category.grouper.name or user.is_superuser %}
                <div class="panel panel-default">
                    <div class="panel-heading">{{ category.grouper.name }}</div>
                    <div class="panel-body table-responsive">
                        <p class="category-desc">
                            {{ category.grouper.description|safe }}
                        </p>

                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th>Service</th>
                                <th class="today">Today</th>
                                {% for day in past %}
                                    <th class="date">{{ day|date:"N d" }}</th>
                                {% endfor %}
                            </tr>
                            </thead>

                            <tbody id="services-body">
                            {% for service in category.list %}
                                <tr>
                                    <td><a href="
                                            {{ service.get_absolute_url }}{{ service.events.latest.start|date:"/Y/m/d" }}">{{ service.name }}</a>
                                    </td>
                                    <td class="status highlight">
                                        <a href="
                                                {{ service.get_absolute_url }}{{ service.events.latest.start|date:"/Y/m/d" }}">
                                            {% with service.events.latest.status as latest_status %}
                                                {% if latest_status %}
                                                    <img src="{{ STATIC_URL }}images/status/{{ latest_status.image }}.png"
                                                         alt="{{ latest_status }} "/>
                                                {% else %}
                                                    <img src="{{ STATIC_URL }}images/status/{{ default.image }}.png"
                                                         alt="{{ default.name }} "/>
                                                {% endif %}
                                            {% endwith %}
                                        </a>
                                    </td>

                                    {% for status in service.last_five_days %}
                                        <td class="status">
                                            <a href="{{ service.get_absolute_url }}/{{ status.day|date:"Y/m/d" }}">
                                                <img src="{{ STATIC_URL }}images/status/{{ status.image }}.png"
                                                     alt="{{ status.image }}">
                                            </a>
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            {% else %}
                <!-- board will not load because user does not have rights -->
            {% endif %}
        {% endfor %}
        {% include "board/_legend.html" %}
    </div>
{% endblock %}

templates/board/service_detail.html
{% extends "base.html" %}
{% block title %}{{ service.name }} | {{ block.super }}{% endblock %}
{% block content %}
    <div id="webservices" class="frame">
        <div class="panel panel-default">
            <div class="panel-heading">{{ service.name }}</div>
            <div class="panel-body table-responsive">
                <p id="service-desc">{{ service.description|safe }}</p>

                <h3 class="date-range">
                    {% if start_date %}
                        {{ start_date|date:"n/j/Y" }}
                    {% endif %}
                </h3>

                <table class="event-log table table-striped table-hover" cellpadding="10">
                    <thead>
                    <tr>
                        <th class="time-header">Time</th>
                        <th class="status-header">Status</th>
                        <th>Message</th>
                    </tr>
                    </thead>
                    <tbody id="events-tbody">
                    {% for e in events %}
                        <tr>
                            <td>{{ e.start|date:"N j, fA T" }}</td>
                            <td class="status highlight">
                                {% if e.informational %}
                                    <img src="{{ STATIC_URL }}images/status/information.png" alt="Information">
                                {% else %}
                                    <img src="{{ STATIC_URL }}images/status/{{ e.status.image }}.png"
                                         alt="{{ e.status.name }}">
                                {% endif %}
                            </td>
                            <td>{{ e.message|safe }}</td>
                        </tr>
                    {% endfor %}
                    {% if no_events %}
                        <tr>
                            <td colspan="3"><h1>{{ no_events }}</h1></td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

{% block toggle_login %}{% endblock %}

{% block heading %}
<h2>Login</h2>
{% endblock %}

{% block content %}
<form action="{% url "mysite_login" %}" method="post" accept-charset="utf-8">
    {{ form|crispy }}
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <input class="btn btn-default" type="submit" value="Login" />
</form>
{% endblock %}

templates/toggle_login.html
{% if user.is_authenticated %}
<ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
        <a class="dropdown-toggle" id="dropuser" data-toggle="dropdown"
            href="#" onclick="javascript:document.getElementById('login-dropdown-menu').style.display='block';">{{ user.username }} <b class="caret"></b></a>
        <ul id="login-dropdown-menu" class="dropdown-menu" role="menu" aria-labelledby="dropuser">
        	{% if user.is_superuser %}
        		<li><a href="/admin/">Admin</a></li>
        	{% endif %}
            <li><a href="{% url 'mysite_logout' %}">Logout</a></li>
        </ul>
    </li>
</ul>
{% else %}
<form class="navbar-form navbar-right" action="{% url 'mysite_login' %}"
        method="post" accept-charset="utf-8">
    <div class="form-group">
        <input class="form-control" type="text" placeholder="Username" name="username">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" placeholder="Password" name="password">
    </div>
    {% csrf_token %}
    <button type="submit" class="btn btn-default">Login</button>
</form>
{% endif %}